Add Klustered episode
RawkodeAcademy/RawkodeAcademy pull request #47
Opened 2023-02-14 15:46 UTC by JOSHUAJEBARAJ

This PR add notes for this [episode](https://www.youtube.com/watch?v=51b2imc6OPM)

2023-02-15 21:55 UTC, rawkode requested changes

2023-02-15 21:55 UTC, rawkode commented on content/klustered/klustered-klustered-marino-john.hcl
> +    scheduled_for = "May 12,2022"
Please use ISO8601 for the date and time

2023-02-15 21:55 UTC, rawkode commented on content/klustered/klustered-klustered-marino-john.hcl
> +    title =  "Marino Wijay & John Anderson | Klustered"
Remove " | Klustered" from title

2023-02-15 21:55 UTC, rawkode commented on content/klustered/klustered-klustered-marino-john.hcl
> +  SUMMARY
Line breaks between sections, SUMMARY, LESSONS LEARNED, etc

2023-02-15 21:55 UTC, rawkode commented on content/klustered/klustered-klustered-marino-john.hcl
> +  This episode of Klustered has Guest `Marino Wijay` and `John Anderson` fighting the misconfigured kubecontext, misconfigured kubelet , misconfigured kubescheduler , misconfigured etcd and misconfig
Don't wrap guest names in quotes

2023-02-16 13:23 UTC, JOSHUAJEBARAJ commented
Hey @rawkode  I messed up my commit history I will make a new PR Ignore this one , apologies for the inconvenience

2023-02-16 13:23 UTC, closed without merging